runtime: nodejs22

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_idle_instances: 1
  max_instances: 2
  min_pending_latency: 5000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80